var loginModule=(function(){var user={firstName:'FirstName',lastName:'LastName',regEmail:'RegEmail',regPassword:'RegPassword',confirmpPassword:'ConfirmPassword',signEmail:'SignEmail',minSignEmail:'MinSignEmail',signPassword:'SignPassword',minSignPassword:'minSignPassword'};return{obj:function(p){return $('#'+ p);},name:function(n){var s={},txt='';switch(n){case user.firstName:txt=lang.first_name_size;break;case user.lastName:txt=lang.last_name_size;break;}
var that=this.obj(n);if(!Tmart.validate.minlength($.trim(that.val()),2)){return{s:false,msg:txt};}
return{s:true,val:that.val()};},email:function(e){var s={},txt='';switch(e){case user.regEmail:case user.signEmail:case user.minSignEmail:txt=lang.need_vaild_mail;break;}
var that=this.obj(e);if(!Tmart.validate.isEmail($.trim(that.val()))){return{s:false,msg:txt};}
return{s:true,val:that.val()};},password:function(p){var s={},txt='';switch(p){case user.regPassword:case user.signPassword:case user.minSignPassword:txt=lang.pwd_least_char;break;}
var that=this.obj(p);if(!Tmart.validate.minlength($.trim(that.val()),5)){return{s:false,msg:txt};}
return{s:true,val:that.val()};},confirmPassword:function(p){var s={},txt='';var that=this.obj(p);if(!Tmart.validate.minlength($.trim(that.val()),5)){return{s:false,msg:lang.retype_pwd};}
if(!Tmart.validate.equalTo($.trim(that.val()),'#'+ user.regPassword)){return{s:false,msg:lang.retype_pwd};}
return{s:true,val:that.val()};},error:function(n){switch(n.target){case'sign':if(n.status){location.reload();return;}
$('input[type=submit]','#min_sign_box').attr("disabled",!1);$('button[type=submit]','#min_sign_box').attr("disabled",!1);$('#min_sign_box').find('.J_response').html(n.message).show();$('#mini-sign').find('.J_login_mask').hide();return;break;case'wishlist':case'checkout':$('#sign_checkout_box').find('.J_login_mask').hide();case'affiliate':case'aff_category':case'aff_custom':$('button[type=submit]','#sign_checkout_box').attr("disabled",!1);$('input[type=submit]','#sign_checkout_box').attr("disabled",!1);$('#'+ n.rf).find('.J_error').html(n.message).show();break;}},doSubmit:function(e,t,call){signTimeout=false;$('button[type="submit"]','input[type="submit"]',"#"+ e).attr("disabled",!0);if(typeof(call)=='function'){call();}}}})();$(function(){$('#register').submit(function(){var $error=$(this).find('.J_error'),redirect=$(this).find('.J_redirect').val();$error.html('');f=loginModule.name('FirstName');if(f.msg){$error.html(f.msg).show();return false;}
l=loginModule.name('LastName');if(l.msg){$error.html(l.msg).show();return false;}
e=loginModule.email('RegEmail');if(e.msg){$error.html(e.msg).show();return false;}
p=loginModule.password('RegPassword');if(p.msg){$error.html(p.msg).show();return false;}
cp=loginModule.confirmPassword('ConfirmPassword');if(cp.msg){$error.html(cp.msg).show();return false;}
if($('#register button[type=submit]').get()){$('#register button[type=submit]').attr('disabled',true);}
if($('#register input[type=submit]').get()){$('#register input[type=submit]').attr('disabled',true);}
return!0;});$('#sigin_in').submit(function(){var $error=$(this).find('.J_error'),redirect=$(this).find('.J_redirect').val();$error.html('');e=loginModule.email('SignEmail');if(e.msg){$error.html(e.msg).show();return false;}
p=loginModule.password('SignPassword');if(p.msg){$error.html(p.msg).show();return false;}
var d={email:e.val,password:p.val,render:'json'};loginModule.doSubmit('sigin_in','',function(){$('#sign_checkout_box').find('.J_login_mask').show();});return!0;});$('#min_sign_box').submit(function(){var $that=$(this),$error=$(this).find('.J_response');$error.html('');e=loginModule.email('MinSignEmail');if(e.msg){$error.html(e.msg).show();return false;}
if($that.find('input[name=option]:checked').val()=='nopassword'){$that.removeAttr('target');}else{$that.attr('target')?'':$that.addAttr('target','signTargetIframe');p=loginModule.password('minSignPassword');if(p.msg){$error.html(p.msg).show();return false;}}
loginModule.doSubmit('min_sign_box','',function(){$('#mini-sign').find('.J_login_mask').show();});var loginUrl=Tmart.HOST+'/zc/user/login/ajax_sign?jsoncallback=?';var postData={email:$that.find('#MinSignEmail').val(),password:$that.find('#minSignPassword').val(),option:$that.find('input[name=option]:checked').val(),};$.getJSON(loginUrl,postData,function(data){if(data.redirect_url&&$.trim(data.redirect_url)!=''){window.location.href=data.redirect_url;}else{if(data.hasOwnProperty("status")){var param={target:'sign',status:data.status,message:data.msg};loginModule.error(param);}}});return false;});});