(function($){var InitArr=[],_InsObj=null,_TOptions=null,isUndefined=function(variable){return typeof variable=='undefined'?true:false;},doaneC=function(e,preventDefault,stopPropagation){var preventDefault=isUndefined(preventDefault)?1:preventDefault;var stopPropagation=isUndefined(stopPropagation)?1:stopPropagation;e=e?e:window.event;if(!e){e=getEvent();}
if(!e){return null;}
if(preventDefault){if(e.preventDefault){e.preventDefault();}else{e.returnValue=false;}}
if(stopPropagation){if(e.stopPropagation){e.stopPropagation();}else{e.cancelBubble=true;}}
return e;},dragContainer=function(menuObj,e,op){e=e?e:window.event;if(op==1){InitArr=[e.clientX,e.clientY];InitArr[2]=parseInt(menuObj.style.left);InitArr[3]=parseInt(menuObj.style.top);document.onmousemove=function(e){try{dragContainer(menuObj,e,2);}catch(err){}};document.onmouseup=function(e){try{dragContainer(menuObj,e,3);}catch(err){}};doaneC(e);}else if(op==2&&InitArr[0]){var menudragnow=[e.clientX,e.clientY];menuObj.style.left=(InitArr[2]+ menudragnow[0]- InitArr[0])+'px';menuObj.style.top=(InitArr[3]+ menudragnow[1]- InitArr[1])+'px';menuObj.removeAttribute('top_');menuObj.removeAttribute('left_');doaneC(e);}else if(op==3){InitArr=[];document.onmousemove=null;document.onmouseup=null;}};boxAlert={show:function(options){var defaults={IsModal:false,BoxContents:false,Url:false,Type:'txt',IsCloseEffects:false,Width:'500px',Height:'250px',IsboxMetrics:false}
var options=$.extend(defaults,options);var thiscobjdiv=$(this),contxt='';if(options.Type=='url'){contxt='<div style="width:'+ options.Width+'px;height:'+ options.Height+'px">';contxt+='<iframe frameborder="0" id="url_content" name="url_content" src="'+ options.BoxContents+'" scrolling="auto" style="width:100%; height:100%;"></iframe>';contxt+='</div>';}else{contxt=options.BoxContents==false?thiscobjdiv.html():options.BoxContents;}
this.close();this.creatBox(contxt,options);},creatBox:function(contxt,options){var $body=$('body');var ofw,ofh;var ww=document.documentElement.clientWidth;var wh=document.documentElement.clientHeight;ofw=ww/2-(options.Width)/ 2;ofh=wh/2-(options.Height+ 50)/ 2;var close=('https:'==document.location.protocol?'https://':'http://')+ location.host+'/includes/templates/tpl_default/images/icons/close.png?v2'
var boxMetrics=options.IsboxMetrics==true?' width:'+ options.Width+'px; height: '+ options.Height+'px':'';var containnInitStr='<div id="boxAlertContainer" style="position: fixed;z-index: 20001; left: '+ofw+'px; top: '+ofh+'px;">';containnInitStr+='<div id="boxDisplay" style="border:12px solid #B7B7B7; position:relative;">';containnInitStr+='<div id="boxMove" style="position:absolute; width:100%; height:30px; cursor:move;"></div>';containnInitStr+='<div style="position:absolute;display:block;right:10px; top:10px;"><a id="boxClose" href="javascript:;"><img src='+close+' /></a></div>';containnInitStr+='<div style="background-color:#FFF; '+ boxMetrics+' ">';containnInitStr+=contxt
containnInitStr+='</div></div></div>';if(options.IsModal==true){$body.append('<div  id="boxOverlay" style="height: '+ $(document).height()+'px; background-color: #000;opacity: 0.6; filter:Alpha(opacity=60); height: 100%;display: block;left: 0;position: absolute;top: 0;width: 100%;z-index: 20000;"></div>');}
$body.append(containnInitStr).show();$AlertContainer=$('#boxAlertContainer'),$boxClose=$('#boxClose');$(document).unbind("keydown").bind("keydown",function(e){var keyCode=window.event?e.keyCode:e.which;if(keyCode==27){$AlertContainer.remove();if(options.IsModal){$('#boxOverlay').remove();}}});$('#boxMove').bind('mousedown',function(e){dragContainer($AlertContainer[0],e,1);});$boxClose.bind('click',function(e){$AlertContainer.remove();if(options.IsModal){$('#boxOverlay').remove();}});},loading:function(IsModal){var ww=document.documentElement.clientWidth;var wh=document.documentElement.clientHeight;var img=('https:'==document.location.protocol?'https://':'http://')+ location.host+'/includes/templates/tpl_default/images/icons/ajax-loader.gif?v3';var loadingImg='<div style="position: absolute;top:'+(wh-128)/2 + 'px; left:' + (ww-128)/2 +'px;"><img src="' + img + '" /></div>';if(IsModal==true){$('body').append('<div id="boxOverlay" style="height: '+ $(document).height()+'px; background-color: #000;opacity: 0.6; filter:Alpha(opacity=60);height: 100%;display: block;left: 0;position: fixed;top: 0;width: 100%;z-index: 20000;">'+loadingImg+'</div>');}else{$('body').append('<div id="boxOverlay">'+loadingImg+'</div>').show();}},close:function(){var $AlertContainer=$('#boxAlertContainer'),$boxOverlay=$('#boxOverlay');$AlertContainer.remove();if($boxOverlay){$boxOverlay.remove();}}}})(jQuery);